### PR TITLE
Integrate database for storing scraping data

### LINKED ISSUE #19: Integrate database for storing scraping data
For all the ideas that we will be working on. would require a database of all the scraped data. It will therefore be very important to have the data stored in a database.

### PR DESCRIPTION
**Pull request by hackrush01**
Made small changes to __main__.py.
Created .gitignore

Fixes #19

### CODE REVIEW

**Comment by hackrush01** [comment]
I think that a `.travis.yml` file is needed for it, configured for python 2.7. Currently it is configured for ruby.

**Comment by madan96** [comment]
Hey @hackrush01 ! Thanks for the PR and sorry to keep you waiting. I was preoccupied with some other work. 

Regarding the PR, what you have done isn't something that we require for our package. By database, I am referring to something like a postgresql database using flask, which will be updated hourly using cronjob.

**Comment by hackrush01** [comment]
What exactly would be the function of the database? Please elaborate. Then I'll try.

**Comment by madan96** [comment]
We are planning to add multiple features to this package like leaderboard for the channels base on IMDb ratings and a recommendation system based on the genre. All this would require multiple instances of scraping from one site and then receiving data from IMDb site, which would take a lot of time. Having a database would help speeding up all these tasks. Postgresql db would have the same table as the one created by you only difference being it would contain data from all the channels that we plan to scrape.

**Pull request closed without merging**
